
package com.hamrahvas.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsBufferSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsBufferSoap {


    /**
     * 
     * @param content
     * @param origShortCode
     * @param username
     * @param number
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MessageUpload", action = "http://tempuri.org/MessageUpload")
    @WebResult(name = "MessageUploadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MessageUpload", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageUpload")
    @ResponseWrapper(localName = "MessageUploadResponse", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageUploadResponse")
    public String messageUpload(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "origShortCode", targetNamespace = "http://tempuri.org/")
        String origShortCode);

    /**
     * 
     * @param content
     * @param origShortCode
     * @param username
     * @param serviceId
     * @param number
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MessageUploadWithServiceId", action = "http://tempuri.org/MessageUploadWithServiceId")
    @WebResult(name = "MessageUploadWithServiceIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MessageUploadWithServiceId", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageUploadWithServiceId")
    @ResponseWrapper(localName = "MessageUploadWithServiceIdResponse", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageUploadWithServiceIdResponse")
    public String messageUploadWithServiceId(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "origShortCode", targetNamespace = "http://tempuri.org/")
        String origShortCode,
        @WebParam(name = "serviceId", targetNamespace = "http://tempuri.org/")
        int serviceId);

    /**
     * 
     * @param username
     * @param origShortCodeList
     * @param contentList
     * @param numberList
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MessageListUpload", action = "http://tempuri.org/MessageListUpload")
    @WebResult(name = "MessageListUploadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MessageListUpload", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageListUpload")
    @ResponseWrapper(localName = "MessageListUploadResponse", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageListUploadResponse")
    public String messageListUpload(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "numberList", targetNamespace = "http://tempuri.org/")
        ArrayOfString numberList,
        @WebParam(name = "contentList", targetNamespace = "http://tempuri.org/")
        ArrayOfString contentList,
        @WebParam(name = "origShortCodeList", targetNamespace = "http://tempuri.org/")
        ArrayOfString origShortCodeList);

    /**
     * 
     * @param username
     * @param origShortCodeList
     * @param serviceIdList
     * @param contentList
     * @param numberList
     * @param password
     * @return
     *     returns com.hamrahvas.webservice.ArrayOfString
     */
    @WebMethod(operationName = "MessageListUploadWithServiceId", action = "http://tempuri.org/MessageListUploadWithServiceId")
    @WebResult(name = "MessageListUploadWithServiceIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MessageListUploadWithServiceId", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageListUploadWithServiceId")
    @ResponseWrapper(localName = "MessageListUploadWithServiceIdResponse", targetNamespace = "http://tempuri.org/", className = "com.hamrahvas.webservice.MessageListUploadWithServiceIdResponse")
    public ArrayOfString messageListUploadWithServiceId(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "numberList", targetNamespace = "http://tempuri.org/")
        ArrayOfString numberList,
        @WebParam(name = "contentList", targetNamespace = "http://tempuri.org/")
        ArrayOfString contentList,
        @WebParam(name = "origShortCodeList", targetNamespace = "http://tempuri.org/")
        ArrayOfString origShortCodeList,
        @WebParam(name = "serviceIdList", targetNamespace = "http://tempuri.org/")
        ArrayOfInt serviceIdList);

}
